import type { Metadata } from 'next';
import './globals.css';

// providers
import { NextAuthProvider } from '@/providers/authProviders';
import { StoreProvider } from '@/providers/storeProvider';

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
};

export default function RootLayout({
   children,
}: {
   children: React.ReactNode;
}) {
   return (
      <html lang="en">
         <body>
            <NextAuthProvider>
               <StoreProvider>{children}</StoreProvider>
            </NextAuthProvider>
         </body>
      </html>
   );
}
