import './globals.css';
import type { Metadata } from 'next';
import { StoreProvider } from '@/providers/storeProvider';
import MuiThemProvider from '@/providers/muiThemProvider';
import { Toaster } from 'react-hot-toast';

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
};

export default function RootLayout({
   children,
}: {
   children: React.ReactNode;
}) {
   return (
      <html lang="en">
         <body>
            <StoreProvider>
               <Toaster />
               <MuiThemProvider>{children}</MuiThemProvider>
            </StoreProvider>
         </body>
      </html>
   );
}
